### ISSUE TITLE
kindly add "hacktober-accepted" label on merged PR

### ISSUE THREAD

**Issue by anjali1102** [junaidrahim/Hacktoberfest-KIIT-2020#121]
pls add  "hacktober-accepted" label on merged PR #51 and of others too else the review will not be taken further

**Comment by junaidrahim** [comment]
The repository already has the topic `hacktoberfest` added. Which is fine according to the new rules. All PRs will be considered

![Screenshot from 2020-10-13 17-00-44](https://user-images.githubusercontent.com/24959303/95855313-cdcc8700-0d75-11eb-9584-6da8b8c551a2.png)

https://hacktoberfest.digitalocean.com/hacktoberfest-update
